version: '3'
services:
    envoy:
        image: envoyproxy/envoy-alpine:v1.14-latest
        depends_on:
            - nginx-gabut
        ports:
            - 8080:8080
            - 9901:9901 #admin here
        volumes:
            - ./envoy/:/etc/envoy/
    
    nginx-gabut:
        build: ./nginx-gabut
        # ports:
        #     - 46440:46440
        